[project]
name = "kRPC-Python-Collection"
version = "0.1.0"
description = "Python scripts for controlling Rockets in the KSP space simulator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "krpc>=0.5.4",
    "scipy>=1.15.2",
    "simple-pid>=2.0.1",
]
